# -*- coding: utf-8 -*-
"""lab1M.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yf9Y1shDz71yuesXoUzixM-s9Mf7vLFq
"""

import numpy as np
import pandas as pd

data = pd.read_csv("iris.csv")

print("First 5 Rows:")
print(data.head())

print("\nDataset Info:")
print(data.info())

print("\nStatistical Summary:")
print(data.describe())

sepal_length = data["sepal_length"].values

print("\nMean:", np.mean(sepal_length))
print("Standard Deviation:", np.std(sepal_length))
print("Maximum:", np.max(sepal_length))
print("Minimum:", np.min(sepal_length))



